# Project information
site_name: StandCloud Documentation
site_url: https://everypinio.github.io/standcloud-doc/
site_author: Everypin
site_dir: public
docs_dir: ./docs

# Repository
repo_name: everypinio/standcloud-doc
repo_url: https://github.com/everypinio/standcloud-doc

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo/logo192.png
  favicon: img/logo/favicon.png
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.path
    - navigation.top
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  navigation:
    position: top

nav:
  - Home: index.md
  - Get started: getting_started.md

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
  - admonition
  - footnotes
  - tables
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      title: Contents
      baselevel: 1

      # Fixes unicode chars in heading anchors. Refs:
      # https://github.com/mkdocs/mkdocs/issues/212#issuecomment-286035214
      # https://facelessuser.github.io/pymdown-extensions/extras/slugs/
      # https://facelessuser.github.io/pymdown-extensions/faq/#function-references-in-yaml
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }

plugins:
  - search
  - roamlinks
  - custom-attributes
  - awesome-pages
  - glightbox
  - tags

  - exclude:
      glob:
        - _unpublished/*
        - "*.tmp"
        - "*.pdf"

  - print-site

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/globe
      link: https://everypin.io/
    - icon: fontawesome/brands/github
      link: https://github.com/everypinio/standcloud-doc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/98bWadmG8J
    - icon: fontawesome/brands/telegram
      link: https://t.me/everypin
    - icon: fontawesome/solid/envelope
      link: mailto:info@everypin.io
